import asyncio
async def main(hmi):
    hmi.tx("any", "page sys_app_run")
    hmi.tx("app_title", "Windows Defender")
    hmi.tx("app_main+", "正在进行安全扫描")
    await asyncio.sleep(1)
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "发现威胁")
    hmi.tx("app_main+", "扫描完成")
    await asyncio.sleep(1)
    hmi.tx("app_main+", "Windows Defender无法处理威胁")
    await asyncio.sleep(1)
    hmi.tx("app_main+", "要爆炸了")
    await asyncio.sleep(1)
    hmi.tx("any", "page boot")